name: Release DevOps with Docker

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2


    
    - name: Build and push
      uses: actions/build-push-action@v2
      with:
        push: true
        tags: devopsdockeruh/coursepage:latest
